name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: 139693b7-b383-4d68-9b37-cdab0c34d98a
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
